name: Submodules Trigger Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["gabrelaTest/test-sand"]
    steps:
      - name: Update gh
      - uses: actions/setup-github-action@v3
        with: 
         action: gh/gh
         
      - name: Repository Dispatch
        run: |
          gh repo dispatch test-submodules-update ${{ matrix.repo }}
