name: Submodules Trigger Update

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["gabrelaTest/test-sand"]
    steps:
      - name: Get token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          permissions: "contents:write"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ steps.get_app_token.outputs.token }}
          repository: ${{ matrix.repo }}
          event-type: test-submodules-update
